### ISSUE TITLE
Split ProGuard rules for RxJava into different artifactIds

### ISSUE THREAD

**Issue by iForests** [yongjhih/android-proguards#5]
Hello,

Since the ProGuard rules for RxJava 1.x and RxJava 2.x are totally different, is it better to split them into different artifactIds (or at least change the publishVersion back to 1.2.2)?

    compile 'com.github.yongjhih.android-proguards:rxjava-pro:1.2.2'
    compile 'com.github.yongjhih.android-proguards:rxjava2-pro:2.0.1'

And in fact, at this moment [Proguard rules are not required for RxJava 2.x](https://github.com/ReactiveX/RxJava/issues/4786).

**Comment by yongjhih** [comment]
sure, I will split it if it's required.

**Comment by yongjhih** [comment]
Seems like rxjava2 has included the rules.
