### ISSUE TITLE
I really don't understand how to us it, can you please provide step by step guide.

### ISSUE THREAD

**Issue by mibrahimdev** [yongjhih/android-proguards#6]
I really don't understand how to us it, can you please provide step by step guide.

**Comment by yongjhih** [comment]
1. Edit `build.grade` in your gradle project
2. Add the following line: `compile 'com.infstory:proguard-snippets:1.0.0'`

That's it.

**Comment by mibrahimdev** [comment]
that's it, that's really simple 👍 
does library version matter? for example, if I'm using Retrofit 1.9, are proguard rules the same as Retrofit 2?

**Comment by yongjhih** [comment]
No, it's not same with target library
